// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNSWsOTJnJK4vQ_JY1o4wlsSSkpMNfq0',
    appId: '1:335462019014:web:35fbfda08211e953828cc7',
    messagingSenderId: '335462019014',
    projectId: 'notes-47df7',
    authDomain: 'notes-47df7.firebaseapp.com',
    storageBucket: 'notes-47df7.appspot.com',
    measurementId: 'G-TKR8GMM8LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtYjHAR2dln1zqsICLLDTF1s6IQPnDjVI',
    appId: '1:335462019014:android:5d13b928370a644b828cc7',
    messagingSenderId: '335462019014',
    projectId: 'notes-47df7',
    storageBucket: 'notes-47df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6htw20vV6Itl4GFESnL82C9UdVsK0EY',
    appId: '1:335462019014:ios:45d037a93d83204d828cc7',
    messagingSenderId: '335462019014',
    projectId: 'notes-47df7',
    storageBucket: 'notes-47df7.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw6htw20vV6Itl4GFESnL82C9UdVsK0EY',
    appId: '1:335462019014:ios:45d037a93d83204d828cc7',
    messagingSenderId: '335462019014',
    projectId: 'notes-47df7',
    storageBucket: 'notes-47df7.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwNSWsOTJnJK4vQ_JY1o4wlsSSkpMNfq0',
    appId: '1:335462019014:web:02cefaa591fc4b7b828cc7',
    messagingSenderId: '335462019014',
    projectId: 'notes-47df7',
    authDomain: 'notes-47df7.firebaseapp.com',
    storageBucket: 'notes-47df7.appspot.com',
    measurementId: 'G-X6LJ51LM57',
  );

}